### ISSUE TITLE
quickly exit without crawling the website

### ISSUE THREAD

**Issue by lyhistory** [pwn0sec/PwnXSS#12]
**Describe the bug**
it just exit after printing the following log:

[02:38:16] [INFO] Starting PwnXSS...
***************
[02:38:16] [INFO] Checking connection to: <url>
[02:38:16] [INFO] Connection estabilished 200

**To Reproduce**
python3 pwnxss.py -u https://the-url/ --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0"

**Expected behavior**
crawling the website

**Screenshots**
![image](https://user-images.githubusercontent.com/1522513/96834716-115d7a00-1475-11eb-8236-1eec1306186a.png)

**Desktop (please complete the following information):**
 - Kali linux 2020.2

**Comment by andripwn** [comment]
**Hi!** @lyhistory we will fixed soon, now is holidays

**Comment by bruvv** [comment]
Same issue here, any update?

**Comment by andripwn** [comment]
Hi, @bruvv 

Thank you for helping our project to make it better in the future, and sorry our team is on vacation until January, please wait for updates on **01/01/21**, if you have any questions. please submit your questions at security@pwn0day.com

**Comment by RAVIPRAJ** [comment]
i think the problem here this for loop in crawler.py in line no 25

i                     f url.startswith("http://") or url.startswith("https://"):
				continue
		
			elif url.startswith("mailto:") or url.startswith("javascript:"):
				continue
			
			elif urljoin(base,url) in self.visited:
				continue

while crawling any website if that website urls contains https:// and there no href="/path/" than this for loop exit without crawling anything in website

**Comment by andripwn** [comment]
Hi @lyhistory this is has been fixed now , thank you.

Kind regards,
@andripwn
