### ISSUE TITLE
--cookie input

### ISSUE THREAD

**Issue by ductrung1901** [pwn0sec/PwnXSS#16]
I don't know how to using --cookie in this tool
I try with --cookie="", --cookie=''.. but didn't work

**Comment by duckstroms** [comment]
fixed release ``v.2``

**Comment by ductrung1901** [comment]
Could you give an example case using --cookie? 
I think your example is not realistic.
You need to give the example with a website  and the input value for --cookie

**Comment by ductrung1901** [comment]
The issue is:
"Json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)"

**Comment by Paerot** [comment]
yea the example doesn't work

**Comment by duckstroms** [comment]
## v0.5 Release (Final):
Bug fixed
Now cookies is supported. (--cookie {})
