### ISSUE TITLE
Does not run but everything is installed.

### ISSUE THREAD

**Issue by Anthonymcqueen21** [pwn0sec/PwnXSS#22]
Hello i decided to use your tool to help me in my hunt for xss vulnerabilities, so long story short i installed everything as needed and attempted to do a simple scan on my target. Well it works but stops with only INFO and then goes back to root (kali@kali:~PwnXSS) so what could be the problem for it not scanning my target successfully is there something else i did not install to make this tool work ?

![image](https://user-images.githubusercontent.com/23253941/122278476-c678f280-ce9b-11eb-8760-91b54e94d76b.png)

**Comment by duckstroms** [comment]
fixed release ``v.2``

**Comment by Anthonymcqueen21** [comment]
What does that mean ?
