### ISSUE TITLE
No Connection Adapter for 'tel://#'

### ISSUE THREAD

**Issue by CMMiraflor** [pwn0sec/PwnXSS#9]
I'm currently using a virtual machine and when i run the code i got this error message.
Im not too familiar with the libraries used, for your kind assistance on this.   Thank you.

![Issue](https://user-images.githubusercontent.com/36496921/90410056-e707ce80-e077-11ea-854d-c02cf5d6bf35.png)

**Comment by CMMiraflor** [comment]
Updating on this.  sense like this happens only with a domain with .tech.  Will start reading on the code and find a fix.

**Comment by andripwn** [comment]
Hi, blocked domain parameter ``-`` in domain
we cannot fixed it.
